version: '3'
services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
#   command: mvn clean spring-boot:run -Dspring.profiles.active=docker
    command: mvn clean spring-boot:run
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - app_env
networks:
  app_env:
    external:
      name: app_env
